# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "moniker_activeresource"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Davide Guerri"]
  s.date = "2013-03-06"
  s.description = "Moniker Ruby and RoR bindings implemented with ActiveResource - See also http://www.unicloud.it"
  s.email = "d.guerri@rd.unidata.it"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/hot_fixes.rb",
    "lib/moniker.rb",
    "lib/moniker/base.rb",
    "lib/moniker/common.rb",
    "lib/moniker/domain.rb",
    "lib/moniker/record.rb",
    "lib/moniker/server.rb",
    "lib/moniker_activeresource.rb",
    "moniker_activeresource.gemspec",
    "test/.gitignore",
    "test/helper.rb",
    "test/test_configuration-sample.yml",
    "test/test_domains.rb",
    "test/test_records.rb",
    "test/test_servers.rb",
    "test/utils.rb"
  ]
  s.homepage = "https://github.com/Unidata-SpA/moniker_activeresource"
  s.licenses = ["GPLv3"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Moniker Ruby and RoR bindings implemented with ActiveResource"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activemodel>, ["~> 3.2.12"])
      s.add_runtime_dependency(%q<activeresource>, ["~> 3.2.12"])
      s.add_runtime_dependency(%q<oj>, ["~> 1.2.9"])
      s.add_runtime_dependency(%q<json>, ["~> 1.7.7"])
      s.add_runtime_dependency(%q<openstack_activeresource>, ["~> 0.5.0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<test-unit>, [">= 0"])
    else
      s.add_dependency(%q<activemodel>, ["~> 3.2.12"])
      s.add_dependency(%q<activeresource>, ["~> 3.2.12"])
      s.add_dependency(%q<oj>, ["~> 1.2.9"])
      s.add_dependency(%q<json>, ["~> 1.7.7"])
      s.add_dependency(%q<openstack_activeresource>, ["~> 0.5.0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<test-unit>, [">= 0"])
    end
  else
    s.add_dependency(%q<activemodel>, ["~> 3.2.12"])
    s.add_dependency(%q<activeresource>, ["~> 3.2.12"])
    s.add_dependency(%q<oj>, ["~> 1.2.9"])
    s.add_dependency(%q<json>, ["~> 1.7.7"])
    s.add_dependency(%q<openstack_activeresource>, ["~> 0.5.0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<test-unit>, [">= 0"])
  end
end

